---
- block:

    - name: unarchive
      become: false
      unarchive:
        src: "{{ node_exporter_repo_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/"
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
      check_mode: false

    - name: "Copy node_exporter to {{ node_exporter_install_dir }}"
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_install_dir }}/node_exporter"
        owner: "root"
        group: "root"
        mode: 0755
        remote_src: yes
      notify: restart node_exporter

- name: create node_exporter config directory
  file:
    path: "{{ node_exporter_config_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
